name: termbox_test
on: [push, pull_request]
jobs:
  termbox_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:                        make clean test
      - run: CFLAGS='-UTB_LIB_OPTS' make clean test # non-egc, non-truecolor
